///////////////////
// USER CONSTANT //
///////////////////

// USER SIGN UP CONSTANT
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

// USER LOGIN CONSTANT
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// USER LOGOUT CONSTANT
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

// USER PROFILE UPDATE CONSTANT
export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";
export const UPDATE_USER_PROFILE_RESET = "UPDATE_USER_PROFILE_RESET";

// USER PASSWORD UPDATE CONSTANT
export const UPDATE_USER_PASSWORD_REQUEST = "UPDATE_USER_PASSWORD_REQUEST";
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS";
export const UPDATE_USER_PASSWORD_FAIL = "UPDATE_USER_PASSWORD_FAIL";
export const UPDATE_USER_PASSWORD_RESET = "UPDATE_USER_PASSWORD_RESET";

// USER PROFILE LOAD CONSTNAT
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

// ALL USER PROFILE LOAD CONSTANT
export const LOAD_ALL_USER_REQUEST = "LOAD_ALL_USER_REQUEST";
export const LOAD_ALL_USER_SUCCESS = "LOAD_ALL_USER_SUCCESS";
export const LOAD_ALL_USER_FAIL = "LOAD_ALL_USER_FAIL";

// USER FRIEND REQUEST SEND AND CANCEL
export const FRIEND_REQUEST_SEND_CANCEL_REQUEST = "FRIEND_REQUEST_SEND_CANCEL_REQUEST";
export const FRIEND_REQUEST_SEND_CANCEL_SUCCESS = "FRIEND_REQUEST_SEND_CANCEL_SUCCESS";
export const FRIEND_REQUEST_SEND_CANCEL_FAIL = "FRIEND_REQUEST_SEND_CANCEL_FAIL";

// USER FRINED REQUEST ACCEPT
export const FRIEND_REQUEST_ACCEPT_REQUEST = "FRIEND_REQUEST_ACCEPT_REQUEST";
export const FRIEND_REQUEST_ACCEPT_SUCCESS = "FRIEND_REQUEST_ACCEPT_SUCCESS";
export const FRIEND_REQUEST_ACCEPT_FAIL = "FRIEND_REQUEST_ACCEPT_FAIL";

// REMOVE FRIEND FROM LIST
export const USER_FRIEND_REMOVE_REQUEST = "USER_FRIEND_REMOVE_REQUEST";
export const USER_FRIEND_REMOVE_SUCCESS = "USER_FRIEND_REMOVE_SUCCESS";
export const USER_FRIEND_REMOVE_FAIL = "USER_FRIEND_REMOVE_FAIL";


////////////////////////////
// POST RELATED CONSTANTS //
////////////////////////////

// GET ALL POST CONSTANT
export const POST_GET_ALL_REQUEST = "POST_GET_ALL_REQUEST";
export const POST_GET_ALL_SUCCESS = "POST_GET_ALL_SUCCESS";
export const POST_GET_ALL_FAIL = "POST_GET_ALL_FAIL";

// GET SINGLE POST CONSTNAT
export const POST_GET_SINGLE_REQUEST = "POST_GET_SINGLE_REQUEST";
export const POST_GET_SINGLE_SUCCESS = "POST_GET_SINGLE_SUCCESS";
export const POST_GET_SINGLE_FAIL = "POST_GET_SINGLE_FAIL";

// GET LOGGED IN USER POSTS CONSTANT
export const POST_AUTH_ALL_POST_REQUEST = "POST_AUTH_ALL_POST_REQUEST";
export const POST_AUTH_ALL_POST_SUCCESS = "POST_AUTH_ALL_POST_SUCCESS";
export const POST_AUTH_ALL_POST_FAIL = "POST_AUTH_ALL_POST_FAIL";

// GET PARTICULAR USER ALL POST CONSTANT
export const POST_RANDOM_ALL_POST_REQUEST = "POST_RANDOM_ALL_POST_REQUEST";
export const POST_RANDOM_ALL_POST_SUCCESS = "POST_RANDOM_ALL_POST_SUCCESS";
export const POST_RANDOM_ALL_POST_FAIL = "POST_RANDOM_ALL_POST_FAIL";

// CREATE NEW POST CONSTANT
export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";

// LIKE A POST BY USER CONSTNAT
export const POST_USER_LIKE_REQUEST = "POST_USER_LIKE_REQUEST";
export const POST_USER_LIKE_SUCCESS = "POST_USER_LIKE_SUCCESS";
export const POST_USER_LIKE_FAIL = "POST_USER_LIKE_FAIL";

// USER POST DELETE CONSTANT
export const POST_USER_DELETE_REQUEST = "POST_USER_DELETE_REQUEST";
export const POST_USER_DELETE_SUCCESS = "POST_USER_DELETE_SUCCESS";
export const POST_USER_DELETE_FAIL = "POST_USER_DELETE_FAIL";


//CLEAR CONSTANT
export const CLEAR_ERRORS = "CLEAR_ERRORS";